---
framework: jest
preRun:
     command:
        - yarn
        - yarn build
preMerge:
  pattern:
    - "__tests__/*/*.spec.tsx"
postMerge:
  pattern: 
    - "__tests__/*/*.spec.tsx"
postRun:
     command:
        - yarn --version
configFile: jest.config.js
version: 1.2
